### ISSUE TITLE
Pstn integrations

### ISSUE THREAD

**Issue by ghost** [pjebs/tokbox#2]
This is a really well done project.

I am trying to get it to work with pstn and did numbers.

Maybe you know some providers for integration from your experience with opentok ?

Would be happy to write an integration between providers and this project in golang.

I am also working on a web UI for admin / management to integrate with this library.

Thanks in advance !!

**Comment by pjebs** [comment]
what is pstn?

**Comment by ghost** [comment]
Publish Switched Telephony Network. Maybe these days its called something esle.

**Comment by pjebs** [comment]
what do you want me to do? I don't even know what PSTN is
